### ISSUE TITLE
Sensor values overflow when they reach value 524288

### ISSUE THREAD

**Issue by VolovarMartin** [sparkfun/SparkFun_OPT4048_Arduino_Library#5]
Hello,

There seems to be a bug in the getAllChannelData function. When I output the raw registers and output color, after I reach the value 524288 (0x80000) there is a big jump in the output, for example:

buff = [40, 7E, EA, 64, ...], calculated color->red value is 519840
buff = [40, 8C, 2A, 74, ...], calculated color->red value is 4294492832, I would expect this value to be 574112 (0x8C2A << 4).

I was able to fix the issue on my arduino, by casting the adc result value to uint32_t before the shifting, e.g. :

before the change
`mantissaCh0 = adc0MSB.result_msb_ch0 << 8;`
after the change
`mantissaCh0 = (uint32_t) adc0MSB.result_msb_ch0 << 8;`

Please check, thanks!

**Comment by edspark** [comment]
Excellent catch, thank you for the issue. I've fixed this [particular behavior in that spot but also elsewhere](https://github.com/sparkfun/SparkFun_OPT4048_Arduino_Library/commit/40ce792484684029b599aca687f8a31abc522ec6), where that struct member needed to be shifted in the exact same context. I'll be pushing a release shortly.
